name: Build Android APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libffi-dev libssl-dev aidl
          pip install --upgrade buildozer cython

      - name: Init and Configure Buildozer
        run: |
          buildozer init
          # Kivy o'rniga pygame qo'shish va SDK litsenziyalarni avto-qabul qilish
          sed -i 's/requirements = python3,kivy/requirements = python3,pygame/g' buildozer.spec
          sed -i 's/# android.accept_sdk_license = False/android.accept_sdk_license = True/g' buildozer.spec

      - name: Build APK with Buildozer
        run: |
          yes | buildozer -v android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: game-apk
          path: bin/*.apk

          
          
